---
# vars file for postgresql
maj: "{{'9.5' if postgresql_version.startswith('9.5') else '9.6' if postgresql_version.startswith('9.6') else postgresql_version|regex_replace('^([0-9]+)[-.].*$','\\1') if postgresql_version != '' else percona_postgresql_version|regex_replace('^([0-9]+)[-.].*$','\\1')   }}"
pg_full_ver: "{{percona_postgresql_version|regex_replace('^([0-9]+)-([0-9]+)[.].*$','\\1.\\2')}}"
pg_deb_url: "https://downloads.percona.com/downloads/postgresql-distribution-{{percona_postgresql_major_ver}}/{{pg_full_ver}}/binary/debian/{{dist}}/x86_64"

pkg:
  el7:
    install_packages:
      - "percona-postgresql{{ percona_postgresql_major_ver }}-libs-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-server-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql{{ percona_postgresql_major_ver }}-contrib-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
  el8:
    install_packages:
      - "percona-postgresql{{ percona_postgresql_major_ver }}-libs-{{ percona_postgresql_version }}.{{ dist }}.x86_64"
      - "percona-postgresql-common-{{percona_postgresql_version2}}.{{dist}}"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-server-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
      - "https://repo.percona.com/ppg-{{ percona_postgresql_major_ver }}/yum/release/8/RPMS/x86_64/percona-postgresql{{ percona_postgresql_major_ver }}-contrib-{{ percona_postgresql_version }}.{{dist}}.x86_64.rpm"
  focal:
    systemd: "postgresql@{{percona_postgresql_major_ver}}-main"
    install_packages:
      - "{{pg_deb_url}}/libpq5_{{ percona_postgresql_version }}.{{ dist }}_amd64.deb"
      - "{{pg_deb_url}}/percona-postgresql-client-common_{{percona_postgresql_version2}}.{{dist}}_all.deb"
      - "{{pg_deb_url}}/percona-postgresql-common_{{percona_postgresql_version2}}.{{dist}}_all.deb"
      - "{{pg_deb_url}}/percona-postgresql-client-{{ percona_postgresql_major_ver }}_{{ percona_postgresql_version }}.{{ dist }}_amd64.deb"
      - "{{pg_deb_url}}/percona-postgresql-{{ percona_postgresql_major_ver }}_{{ percona_postgresql_version }}.{{ dist }}_amd64.deb"

pg_conf_dir: "{{ '/var/lib/pgsql/'+maj+'/data' if ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux' else '/etc/postgresql/'+maj+'/main'}}"
pg_data_dir: "{{ '/var/lib/pgsql/'+maj+'/data' if ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux' else '/var/lib/postgresql/'+maj+'/main'}}"
pg_systemd_svc: "{{ pkg[dist].systemd if ('systemd' in pkg[dist]) and percona_postgresql_version !='' else os[dist][soft].systemd_service if soft else db_systemd_service }}"
