- name: Download helm
  get_url:
    url: https://get.helm.sh/helm-v3.3.4-linux-amd64.tar.gz
    dest: /opt/helm.tar.gz
- name: Unpack helm binary
  unarchive:
    remote_src: yes
    src: /opt/helm.tar.gz
    dest: /usr/bin
    extra_opts:
      - "--strip-components=1"
      - "linux-amd64/helm"
    creates: /usr/bin/helm
#- name: Helm Setup tasks
#  when: install_only == ''
#  include_tasks: helm_setup.yaml
