---
# tasks file for vault
- name: Create SSL certificates
  command:
    cmd: /bin/bash /vagrant/tools/generate_ssl_certs.sh vault.percona.local client.percona.local
    creates: /root/certs.tar.gz

- name: Make Vault CA trusted
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux')
  shell:
    cmd: >-
      cp /root/ssl/ca.pem /etc/pki/ca-trust/source/anchors/vault-local.pem ;
      update-ca-trust 
    creates: /etc/pki/ca-trust/source/anchors/vault-local.pem

- name: Install vault package deps
  package:
    name: "{{item}}"
    state: present
  with_items: openssl, unzip

- name: Download and unpack vault binary
  ansible.builtin.unarchive:
    src: https://releases.hashicorp.com/vault/{{vault_version}}/vault_{{vault_version}}_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    creates: /usr/local/bin/vault

- name: Setup Vault
  when: install_only == ''
  command:
    cmd: /bin/bash /vagrant/tools/setup_vault_server.sh vault.percona.local
    creates: /etc/vault/vault.hcl
