apiVersion: v1
kind: Secret
metadata:
  name: cluster1-backrest-repo-config
type: Opaque
data:
  aws-s3-key: UkVQTEFDRS1XSVRILUFXUy1BQ0NFU1MtS0VZ
  aws-s3-key-secret: UkVQTEFDRS1XSVRILUFXUy1TRUNSRVQtS0VZ
