apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigning-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monitoring-service-tls
spec:
  commonName: monitoring.example.com
  secretName: tls-minio
  dnsNames:
    # Ingress domain
    - minio.example.com
    # Internal domain
    - monitoring-service.default.svc.cluster.local
  issuerRef:
    name: selfsigning-issuer
