---
# tasks file for benchmarks
- name: install apt db packages (pkg name)
  when: >
    sysbench_version != '' and
    (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
  apt:
    name: "{{ os[dist].sysbench.install_packages }}"
- name: install db packages
  when: >
    sysbench_version != '' and
    (ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'OracleLinux')
  yum:
    name: "{{ os[dist].sysbench.install_packages }}"
    state: present
    disable_gpg_check: "{{ 'yes' if os[dist].sysbench.install_packages[0].startswith('http') else 'no' }}"

- name: Prepare sysbench oltp read write database
  when: >
    (
    sysbench_version != '' or
    sysbench_pg != '' or
    sysbench_mysql != ''
    ) and db_password != '' and
    ('sysbench_oltp_read_write' in db_features.split(','))
  command:
    cmd: /bin/bash /vagrant/tools/setup_sysbench.sh "{{ 'pg' if sysbench_pg != '' else 'mysql'}}" "{{sysbench_pg if sysbench_pg != '' else sysbench_mysql if sysbench_mysql != '' else ''}}" "{{ db_password }}"
    creates: /usr/local/bin/run_sysbench.sh
